
package net.weg.soa.eng.maestro.documentviewer;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

import net.weg.eng.MaestroException;




/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3.2-06/22/2009 08:27 PM(mockbuild)-SNAPSHOT
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "DocumentViewer", targetNamespace = "http://soa.weg.net/eng/maestro/documentViewer", wsdlLocation = "file:/C:/Projetos/maestro/development/maestro/src/DocumentViewer.wsdl")
public class DocumentViewer
    extends Service
{

    private final static URL DOCUMENTVIEWER_WSDL_LOCATION;
   
    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = net.weg.soa.eng.maestro.documentviewer.DocumentViewer.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Projetos/maestro/development/maestro/src/DocumentViewer.wsdl");
        } catch (MalformedURLException e) {
        	throw new MaestroException(e.getMessage());
        }
        DOCUMENTVIEWER_WSDL_LOCATION = url;
    }

    public DocumentViewer(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DocumentViewer() {
        super(DOCUMENTVIEWER_WSDL_LOCATION, new QName("http://soa.weg.net/eng/maestro/documentViewer", "DocumentViewer"));
    }

    /**
     * 
     * @return
     *     returns DocumentViewerSoap
     */
    @WebEndpoint(name = "DocumentViewerSoap")
    public DocumentViewerSoap getDocumentViewerSoap() {
        return super.getPort(new QName("http://soa.weg.net/eng/maestro/documentViewer", "DocumentViewerSoap"), DocumentViewerSoap.class);
    }

}
