
package net.weg.soa.eng.maestro.documentviewer;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DocumentViewerSoap", targetNamespace = "http://soa.weg.net/eng/maestro/documentViewer")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DocumentViewerSoap {


    /**
     * 
     * @param documentViewerRequest
     * @return
     *     returns net.weg.soa.eng.maestro.documentviewer.DocumentViewerResponse
     */
    @WebMethod(action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "DocumentViewerResponse", targetNamespace = "http://soa.weg.net/eng/maestro/documentViewer", partName = "documentViewerResponse")
    DocumentViewerResponse updateDocumentViewerCache(
        @WebParam(name = "DocumentViewerRequest", targetNamespace = "http://soa.weg.net/eng/maestro/documentViewer", partName = "documentViewerRequest")
        DocumentViewerRequest documentViewerRequest);

}
